#Set LS colors
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

#Default Editor
export EDITOR=vim

# subl cmd
alias "subl"="open $0 -a \"Sublime Text\""

# Set the cmd prompt
export PS1="\e[0;35m[\#] \u@\h \W> \e[m"

