#Set LS colors
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

#Default Editor
export EDITOR=vim

# subl cmd
alias "subl"="open $0 -a \"Sublime Text\""

# macdown cmd
alias "macdown"="open $0 -a \"Macdown\""

# Set the cmd prompt
export PS1="\[\e[0;33m[\#] \u@\h \W>\e[m\] "
# 0;35

